import { createAccount, createClient } from "genlayer-js";
import { studioNext } from "./network.mjs";
import { TransactionStatus, transactionResultNumberToName } from "genlayer-js/types";

const contract = process.env.INCIDENTGATE_CONTRACT_ADDRESS;
const policy = process.env.INCIDENTGATE_KRAKEN_POLICY;
const existingIntent = process.env.INCIDENTGATE_KRAKEN_INTENT?.trim();
if (!contract || (!policy && !existingIntent)) throw new Error("Missing contract and Kraken policy/intent");
async function keys() { if(process.stdin.isTTY&&process.stdin.setRawMode)process.stdin.setRawMode(true); process.stdin.resume(); const values=[]; let value=""; for await (const chunk of process.stdin) for (const c of String(chunk)) { if (c === "\n" || c === "\r") { if (value) { values.push(value.trim()); value=""; if (values.length===2) { if(process.stdin.isTTY&&process.stdin.setRawMode)process.stdin.setRawMode(false); return values; } } } else value += c; } return values; }
const secrets=await keys(); const ownerAccount=createAccount(`0x${secrets[0].replace(/^0x/,"")}`); const agentAccount=createAccount(`0x${secrets[1].replace(/^0x/,"")}`); secrets.fill("");
const reader=createClient({chain:studioNext,account:ownerAccount}); const agent=createClient({chain:studioNext,account:agentAccount});
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function failure(tx, receipt) { const leader=tx?.consensus_data?.leader_receipt?.[0]; const execution=String(leader?.execution_result??"").toUpperCase(); const state=String(leader?.result?.status??"").toUpperCase(); const consensus=String(tx?.resultName??transactionResultNumberToName?.[String(tx?.result)]??"").toUpperCase(); if(execution&&execution!=="SUCCESS")return String(leader?.result?.payload?.readable??leader?.result?.payload??execution); if(["ROLLBACK","ERROR","FAILED"].some(x=>state.includes(x)))return String(leader?.result?.payload?.readable??leader?.result?.payload??state); if(consensus&&!['AGREE','MAJORITY_AGREE'].includes(consensus))return `consensus ${consensus}`; return ""; }
async function write(label, fn, args, client=agent) { const estimate=await client.estimateTransactionFeesForWrite({address:contract,functionName:fn,args,value:0n}); const hash=await client.writeContract({address:contract,functionName:fn,args,value:0n,fees:{distribution:estimate.distribution,feeValue:estimate.feeValue}}); process.stdout.write(`${label}: ${hash}\n`); const receipt=await client.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED,interval:2000,retries:180}); let tx=receipt; try{tx=await client.getTransaction({hash});}catch{} const rejected=failure(tx); if(rejected)throw new Error(`${label}: ${rejected}`); process.stdout.write(`${label}: FINALIZED\n`); return hash; }
async function read(fn,args=[]) { let value=await reader.readContract({address:contract,functionName:fn,args}); if(typeof value==='string')value=JSON.parse(value); if(value&&typeof value==='object'&&Object.keys(value).length===1&&'result'in value)value=typeof value.result==='string'?JSON.parse(value.result):value.result; return value; }
const version=await read("get_contract_version"); if(version.name!=="IncidentGate"||version.version!==11||version.schema!=="autonomous-incident-gate-v11-sdk-v03")throw new Error("Contract handshake failed");
const tag=String(Date.now()); const intent=existingIntent||`kraken-retry-${tag}`; let create=null; if(!existingIntent){create=await write("krakenRetry.create","create_intent",[intent,policy,1000n,`kraken-retry-nonce-${tag}`]); await write("krakenRetry.schedule","schedule_assessment",[intent,300]); await new Promise(resolve=>setTimeout(resolve,32000));} let before=await read("get_intent",[intent]); let assess=null; if(before.status==="ASSESSMENT_SCHEDULED"){assess=await write("krakenRetry.assess","assess_intent",[intent],reader); before=await read("get_intent",[intent]);} let execute=null; if(before.status==="AUTHORIZED"){execute=await write("krakenRetry.execute","execute_intent",[intent,before.authorization_digest],agent); for(let attempt=0;attempt<30;attempt++){before=await read("get_intent",[intent]); if(before.status==="EXECUTED")break; await new Promise(resolve=>setTimeout(resolve,3000));}} const state=before; process.stdout.write(`KRAKEN_RETRY_COMPLETE ${JSON.stringify({intent,create,assess,execute,state},null,2)}\n`);
